SET(NETWORK_OFFLOADER_FOUND FALSE)
SET(NETWORK_OFFLOADER_LIBRARY "")
SET(NETWORK_OFFLOADER_INCLUDE_DIR "")

IF(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/NetworkOffloader/README.md")
	SET(NETWORK_OFFLOADER_FOUND true)
	SET(NETWORK_OFFLOADER_LIBRARY "netoff")
	SET(NETWORK_OFFLOADER_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/NetworkOffloader/include")
ENDIF()
    
